Update bitcoin-like nodes
GoStartupsLtd/cryptonodes-docker pull request #29
Opened 2023-06-12 12:44 UTC by DeanDonkov

2023-06-22 09:22 UTC, ValeriD requested changes

2023-06-22 09:22 UTC, ValeriD commented on Litecoin/Dockerfile
>  EXPOSE 22556
Invalid port

2023-06-22 09:22 UTC, ValeriD commented on Litecoin/Dockerfile
> +COPY --from=build /usr/local/bin/litecoind /usr/local/bin
Disabled the CLI.

2023-06-26 13:40 UTC, DeanDonkov commented on BitcoinCash/Dockerfile
> +RUN apt update && apt upgrade -y && apt install -y curl gpg wget libssl-dev build-essential cmake git libboost-chrono-dev libboost-filesystem-dev libboost-test-dev libboost-thread-dev libevent-dev li
No, because every node is dynamically compiled and there would be missing dependencies. Resolving all comments about this.

2023-06-27 07:40 UTC, ValeriD requested changes

2023-06-27 07:40 UTC, ValeriD commented on Bitcoin/Dockerfile
>  RUN chmod 777 ./run.sh
It would be better to give only executable permissions for this script and only for the current user.

2023-06-27 07:40 UTC, ValeriD commented on BitcoinGold/Dockerfile
>  COPY --from=build /usr/local/bin/bgoldd /usr/local/bin
Missing CLI.

2023-06-27 07:40 UTC, ValeriD commented on BitcoinGold/Dockerfile
>  RUN chmod 777 ./run.sh
Fix persmissions.

2023-06-27 07:40 UTC, ValeriD commented on Dogecoin/Dockerfile
>  RUN chmod 777 ./run.sh
Fix the permissions.

2023-06-27 07:40 UTC, ValeriD commented on Litecoin/Dockerfile
>  RUN chmod 777 ./run.sh
Fix the permissions.

2023-07-05 13:04 UTC, ValeriD requested changes

2023-07-05 13:04 UTC, ValeriD commented on Dogecoin/Dockerfile
>  EXPOSE 22555
Dogecoin port is 22556

2023-07-06 14:55 UTC, ValeriD approved these changes

2023-07-08 15:11 UTC, merged